---
- hosts: localhost
  remote_user: root
  roles:
  - chmduquesne.iptables_persistent
  
  vars_prompt:
  - name: headnode_name
    prompt: "Please insert the name of the headnode: " 
  
  - name: worker_MAC_address
    prompt: "Please insert the MAC address of the first worker node: "
  
  tasks: 
  - include_tasks: "step.1.yml"
  - include_tasks: "step.2.yml"
    vars:
      headnode: headnode_name
      worker_MAC: worker_MAC_address